# Generated by Django 2.2.7 on 2020-08-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='nombre',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
